# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./ctogether_vs.h
SOURCES += ./ctogether_vs.cpp \
    ./main.cpp
FORMS += ./ctogether_vs.ui
RESOURCES += ctogether_vs.qrc
